---
title: "Table-Environment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{04-Table-Env}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## working with tables


Tables are commonly used in RJ articles to display data in a tabular format. However, there are differences in the way tables are handled by LaTeX and HTML. 

LaTeX tables have more customization and are usually optimized for printing, whereas the web articles need tables optimized for varying sizes of media. 

pandoc converts most of the tables somewhat easily, but is unable to do well with table customization packages and complex tables.

Some pandoc extensions are used in order to tackle them, they are : `simple_tables`, `pipe_tables`

Limited Multicolumn support is included.
```latex
\begin{table*}[t!]
\begin{center}
\begin{tabular}{l | llll }
 \hline
 \multicolumn{1}{c |}{EXAMPLE} & \multicolumn{2}{c}{$X$} &
\multicolumn{2}{c}{$Y$} \\
 \hline
  & 1 & 2 & 1 & 2 \\
 EX1  & X11 & X12 &  Y11  & Y12 \\
 EX2  & X21 & X22 &  Y21  & Y22 \\
 EX3  & X31 & X32 &  Y31  & Y32 \\
 EX4  & X41 & X42 &  Y41  & Y42\\
 EX5  & X51 & X52 &  Y51  & Y52 \\
\hline
\end{tabular}
\label{table1} \caption{An Example Table with Multicolumn}
\end{center}
\end{table*}
```
The above example illustrates a complicated table, which the texor package can handle through a subroutine and preprocessing step to transform the LaTeX code.

1. The Stream Editor modifies the \multicolumn{..} to \multicolumnx{..}
2. Then a LaTeX macro redefines the \multicolumnx{..} to \multicolumn{---}, which is accepted by pandoc.
3. Finally pandoc reads the table and transforms it to markdown.


Also note that the stream editor is used to rename `table*` environment to `table` environment because the markdown/HTML will not support the specific changes `table*` environment will bring.

The Resulting Markdown Generated would look like :

```markdown
::: center
::: {#table1}
  -------------------------------------
  EXAMPLE   \(X\)         \(Y\)   
  --------- ------- ----- ------- -----
            1       2     1       2

  EX1       X11     X12   Y11     Y12

  EX2       X21     X22   Y21     Y22

  EX3       X31     X32   Y31     Y32

  EX4       X41     X42   Y41     Y42

  EX5       X51     X52   Y51     Y52
  -------------------------------------

  : Table 1: An Example Table with Multicolumn
:::

[]{#table1 label="table1"}
:::
```
