on:
  push:
    branches:
      - main
      - master
    tags:
      -'*'

name: R_cmd_check

jobs:
  rcmdcheck:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        pandoc: ['3.1.2','2.17','2.14.2', '2.13']
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
            r-version: 'devel'
      - uses: pandoc/actions/setup
        with:
            version: ${{ matrix.pandoc_version }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
            extra-packages: any::rcmdcheck
            needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
            args: 'c("--no-manual", "--as-cran")'
            error-on: '"error"'
            check-dir: '"check"'
